#!/bin/bash

NAME=woocommerce-paystand
DIR="${NAME}"
DIST=../../dist/woocommerce
VERSION=`cat version.txt`

echo Creating ${DIST}/${NAME}-${VERSION}.zip
zip -r ${DIST}/${NAME}-${VERSION}.zip ${DIR}
echo
echo Creating ${DIST}/${NAME}-${VERSION}.tgz
tar cvfz ${DIST}/${NAME}-${VERSION}.tgz ${DIR}

