#!/bin/bash

DIST=../../dist
VERSION=`cat version.txt`

echo Creating ${DIST}/woocommerce-paystand-${VERSION}.zip
zip -r ${DIST}/woocommerce-paystand-${VERSION}.zip woocommerce-paystand
echo Creating ${DIST}/woocommerce-paystand-${VERSION}.tgz
tar cvfz ${DIST}/woocommerce-paystand-${VERSION}.tgz woocommerce-paystand

