#!/bin/bash

DIST=../../dist
VERSION=`cat version.txt`

echo "Creating zip file"
zip -r ${DIST}/woocommerce-paystand-${VERSION}.zip woocommerce-paystand
echo "Creating tgz file"
tar cvfz ${DIST}/woocommerce-paystand-${VERSION}.tgz woocommerce-paystand

