#!/bin/bash

NAME=woocommerce-paystand
DIR="${NAME}"
DIST=./
VERSION=`cat version.txt`

echo Deleting ${DIST}/${NAME}-${VERSION}.zip
rm -f ${DIST}/${NAME}-${VERSION}.zip
echo Deleting ${DIST}/${NAME}-${VERSION}.tgz
rm -f ${DIST}/${NAME}-${VERSION}.tgz

