<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_individual</name>
   <tag></tag>
   <elementGuidId>83da431d-9676-4a3e-a799-1b88e6844f7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;select_option_18&quot;)/div[@class=&quot;md-text&quot;]/span[@class=&quot;ng-binding&quot;][count(. | //*[@ref_element = 'Object Repository/Page_My Account  MyWordpress (2)/iframe_paystand_checkout_ifram']) = count(//*[@ref_element = 'Object Repository/Page_My Account  MyWordpress (2)/iframe_paystand_checkout_ifram'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>individual</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_option_18&quot;)/div[@class=&quot;md-text&quot;]/span[@class=&quot;ng-binding&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_My Account  MyWordpress (2)/iframe_paystand_checkout_ifram</value>
   </webElementProperties>
</WebElementEntity>
